### ISSUE TITLE
Typo on page V - Errata

### ISSUE THREAD

**Issue by aryehraber** [hootlex/the-majesty-of-vuejs#1]
Just started reading the book and came across a small spelling error:

github _reposiroty_ should be github **repository**, or actually GitHub repository 😉 

By the way, congrats on the book! Will post more issues if I find other errors.

**Comment by hootlex** [comment]
Hi @aryehshai 

Thank you for letting us know.
We will correct it in the next update.

I hope you enjoy the book. :)
