### ISSUE TITLE
preventing submit in calculate method

### ISSUE THREAD

**Issue by mbprabowo** [hootlex/the-majesty-of-vuejs#11]
Hello guys, i just read the demo and it is very good. Keep up the good work! 

I found that methods calculate in page 8 that does not include the event in the function. So its still submitting the form.

![issue](https://cloud.githubusercontent.com/assets/17063448/16977768/423bfbc8-4e82-11e6-8b12-cfdb1f80166c.png)

**Comment by hootlex** [comment]
There is no need to include the event.
If you run the code of this example you will see that it prevents the form from submitting.

Thanks for your contribution. :)

**Comment by cody1991** [comment]
P70.

Vue.js provides two event modifiers for v-on to prevent the event default behavior:
1. .prevent
2. .stop

.stop is event.stopPropagation(); not to prevent the event default behavior

the click event's propagation will be stopped

but 

<button type="submit" @click.stop="calculate">Calculate</button>

will still reload the page.
