### ISSUE TITLE
Error on Calculator Example

### ISSUE THREAD

**Issue by stevepop** [hootlex/the-majesty-of-vuejs#12]
On page 51, (Interactivity) I believe there is an error in the calculator example.

```
 methods: {
        calculate: function() {
          event.preventDefault();
          switch (this.operator) {
            case "+":
              this.c = this.a + this.b
              break;
            case "-":
              this.c = this.a - this.b
              break;
            case "*":
              this.c = this.a * this.b
              break;
            case "/":
              this.c = this.a / this.b
              break;
          }
        }
      }
```

The issue here is `event.preventDefault`. The event argument is not passed, therefore event.preventDefault() will not work. This will be a no-brainer for those who are used to javascript and basics of Vue.js but for others it might be a stumbling block.

**Comment by pongoman** [comment]
There is no need to include the event here.
If you run the code of this particular example you will see that it prevents the form from submitting.

Thanks for your contribution.

**Comment by stevepop** [comment]
HI @pongoman, I tried the example before I posted this however what i did not mention was that I am using Firefox and it does not work unless you pass the event. I tried in Chrome and it did work without passing the event. Just thought I should note this. Thanks

**Comment by pongoman** [comment]
Hello @stevepop, you are right it does work on Chrome but not on Firefox. I will fix this on the next update. Thank you for taking time to note this.
