### ISSUE TITLE
Painting homework: Why using computed data?

### ISSUE THREAD

**Issue by FNGR2911** [hootlex/the-majesty-of-vuejs#13]
Hi everybody! First of all: what a great book, thank you!

I got a question about the homework 7.4: If i take a look at your potential solution you're using computed data to generate the styleObject and I'm not sure why? I got it working with the following code (plain object with v-model on input) and I'm not sure if it's maybe the wrong way?!

index.html

``` html
<body :style="bgColor">
    <div id="app">
      <div class="container">

        <h1>Paint this background!</h1>

        <input type="color" v-model="bgColor.backgroundColor" />

      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.js" charset="utf-8"></script>
    <script src="app.js" charset="utf-8"></script>
</body>
```

app.js

``` javascript
new Vue({
  el: 'body',

  data: {
    bgColor: {
      backgroundColor: "#00cc00"
    }
  }
});
```

It's working fine without the bgColor object stored as computed object. So which is the better approach and why?

**Comment by hootlex** [comment]
Hi @FNGR2911, thank you for the kind words.

Good note. We use a computed property because we were using class binding in another solution we  made, before deciding to do it this way. We'll actually migrate the current solution to use a simple variable.

**Comment by pongoman** [comment]
Thank you @FNGR2911 , we have changed the potential solution of chapter 7 according to your suggestion.
