### ISSUE TITLE
Chapter 16: local: data and story.id

### ISSUE THREAD

**Issue by FNGR2911** [hootlex/the-majesty-of-vuejs#14]
Hey everybody! One question and a hint for everybody in chapter 16:
1. What is and why are you using "local: 'data'" in the data return of Stories.vue on page 221? Never talked about that before and just want to know what is it for?
2. The hint (should be more clear in the description): On page 222 you're saying: "A noteworthy change is the addition of an id to each story within store.js." but there is no example so I added the ID to every Story as a number. But the $route.param given back is a string. So I a struggled some minutes why it isn't working. So how to deal with that? I mean an ID as a string doesn't sound really good. Maybe the best way is to convert the param to an number before searching through store.js?

thank you for help!! 

EDIT: so i've got it working with this in Edit.vue:

``` javascript
    methods: {
      isTheOne(story) {
        const routeID = parseInt(this.$route.params.storyId, 10);
        return story.id === routeID;
      },
    }
```

**Comment by hootlex** [comment]
Hey @FNGR2911 and sorry for the late reply.
1. In 221, we use the variable `local` with the value of  `'data'` to demonstrate that you can use the global `store` while you can have local data within component's `data` array.
2. Yeah, you can convert it to an integer if needed. Also, you can use `story.id == routeID` (with 2 `=`) without having to do any conversions.
