### ISSUE TITLE
Error this.$set is not a function

### ISSUE THREAD

**Issue by stevepop** [hootlex/the-majesty-of-vuejs#17]
I followed the code in Chapter 10, section 10.3.1 with the following ready function;

```
ready: function() {
            // GET request
            this.$http({url: '/api/stories', method: 'GET'}).then(function (response) {
                var storiesReady = response.data.map(function(story){
                    story.editing = false;
                    return story
                })

            this.$set('stories', storiesReady)
            })
}
```

When I executed this, I got the error in my console; `(index):105 Uncaught (in promise) TypeError: this.$set is not a function(…)`. The only way I could make this work was to do the following;
Assign var vm to this before the server request var `var vm = this`
Then set the data;

vm.$set('stories', storiesReady) 

Any thoughts?

**Comment by hootlex** [comment]
Having a quick look at the [homework's solution of chapter 10](https://github.com/hootlex/the-majesty-of-vuejs/blob/master/homework/chapter10/js/app.js), I see that using `vm.$set` is the right way to do it.

We'll update the code block in the book. Thanks for pointing it out.
