### ISSUE TITLE
Exmaples of Vue 1.x => Vue 2.0?

### ISSUE THREAD

**Issue by ivanberry** [hootlex/the-majesty-of-vuejs#21]
Hi, thanks for this **majesty-for-vuejs** book, But I have some questions on examples and  some deprecated modifiers. 
1. Since the `sync` has been deprecated, How to finish the **story** chapter ?
2. Will you update the book with Vue 2.0? especial for the deprecated part.
3. And how to get these updates of the book, BTW, I get this book from **leanpub**?

Thanks for your effort again!

**Comment by hootlex** [comment]
Hello @ivanberry,

Of course, we will update all the examples to Vue 2.
We are currently working on the update (I just finished the stories example, which is kinda funny 😄 ).
I expect to publish the first version of the new book next week.

If you like to learn more details about the [The Majesty of Vue.js 2](https://leanpub.com/vuejs2) check the official [announcement](https://vuejsfeed.com/blog/updates-about-the-majesty-of-vue-js-2).

Thanks.

**Comment by ivanberry** [comment]
@hootlex ,

Thanks :+1: 
I am working hard to be Majesty with your book! :smile:

**Comment by hootlex** [comment]
I am happy to hear that. 😊
