### ISSUE TITLE
If you use Vuejs@2.0

### ISSUE THREAD

**Issue by wikak** [hootlex/the-majesty-of-vuejs#23]
Vue instance will be mounted on **container**. I don't know why ` el: 'body',` didn't work for me.
**In my js file**
```
new Vue({
    el: '.container',
})
```

**Comment by Scxty** [comment]
> Level beginners
> 
> **in my html file**
> 
> ```
> <div id="app">
>         <h1 v-show="gender === 'homme'">Hello Mister {{name}}</h1>
>         <h1 v-show="gender === 'femme'">Hello Miss {{name}}</h1>
> 
>         <p> Entrer your gender</p>
>         <input v-model="gender"></input>
>         <br><br><br> 
>         <p> Entrer your name</p>
>         <input v-model="name"></input>
>  </div>
> ```
> **In my js file**
> 
> ```
> new Vue({
>     el: '#app',
>     data: {
>         gender: '',
>         name:''
>     }
> })
> ```
