### ISSUE TITLE
Unnecessary discrimination on p.19

### ISSUE THREAD

**Issue by minthemiddle** [hootlex/the-majesty-of-vuejs#5]
In the homework on p.19 you ask us to output `Enter a valid gender, human` if neither `male` or `female` is entered. This might be really offensive to people who cannot or do not want to select either gender. I feel it is totally unnecessary here, because you could simply output something different, just like `So you can't decide. Fine!`. I feel coding should not be about excluding people.

**Comment by hootlex** [comment]
I am sorry, I hadn't thought that I was excluding people this way. We will update this warning in the next book update. I'll also update exercise's solution.
Thanks for pointing out.
