### ISSUE TITLE
Sir can you publish an advance version book that cover ES 6 and making a Single Page Application?

### ISSUE THREAD

**Issue by yoongkang0122** [hootlex/the-majesty-of-vuejs#6]
I like the way you express in your book. I hope i can learn more with you.

**Comment by hootlex** [comment]
Hey @yoongkang0122 I am really glad you like our book.
We plan on writing a new book for building Single Page Applications using ES6 and Vuex, but I can't promise. :)

**Comment by yoongkang0122** [comment]
This is great, i am looking forward for your new book =]

**Comment by hootlex** [comment]
Thanks for your interest and support.
To get the latest news about our Book [follow us on twitter](https://twitter.com/tmvuejs).

**Comment by eklem** [comment]
👍
