### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by yitzhakbg** [hootlex/the-majesty-of-vuejs#7]
On page 12 of the sample:
_Above there is the same example as before with one difference, there is an input **binded** to the a variable. The desired outcome is to change the value of the **binded** attribute and update instantly the result of b. But what you will notice here, is that it does not work as we would expect._

The word **binded** is incorrect English. The correct word is **bound**.
Also, suggestion for better colloquial writing would be:
_The above example is the same as the previous, but with one difference: An input is bound to the a variable. The desired outcome would be to change the value of the bound attribute and immediately update the result of b. But notice that it does not work as expected._

**Comment by pongoman** [comment]
Thank you for taking time to share your suggestions.  We will consider them in the next update.
I will change the word right away.
