### ISSUE TITLE
Correct Time to Install Bootstrap?

### ISSUE THREAD

**Issue by pmbaumgartner** [hootlex/the-majesty-of-vuejs#9]
Thanks for the book, I'm really enjoying it so far. I do have one concern re: bootstrap.

The reader isn't directed to install bootstrap until chapter 4. However, the example code and images for the homework in chapters 2 and 3 both include bootstrap. I think this is a little confusing to the reader if they expect their homework from chapters 2 and 3 to look like it's presented in the book. 

My suggested change would be to inform the reader about bootstrap as a pre-requisite, so that they can include it for the homework exercises. Alternatively, the intro to bootstrap can stay where it us, but the images in the book for homework exercises before bootstrap is installed could be updated to reflect what it looks like in vanilla HTML/CSS.

**Comment by pongoman** [comment]
You are right about the images of homework but we decided to do it that way to get better screenshots. Because there might be some confusion I will add notes clarifying this. Thank you for your feedback, enjoy the book!
